# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'docker-registry.grenzebach.com/dotnet-core-api:$(build.buildId)'

steps:
#- bash: |
#    mkdir -p /etc/docker/certs.d/104.214.239.25:443
#    echo -n | openssl s_client -connect 104.214.239.25:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/docker/certs.d/104.214.239.25:443/registry.crt
# some comment
- script: |
  docker build -f Dockerfile -t $(imageName) .
  docker login -u $(dockerId) -p $(pswd) docker-registry.grenzebach
  docker push $(imageName)
